=== guo-Parsec/pinapple-project/query-config.dtd
<!ELEMENT config (query-params result-map convert-list)>
        <!ELEMENT query-params (param*)>
        <!ELEMENT param ()>
        <!ATTLIST param
                field-name CDATA #REQUIRED
                param-name CDATA #IMPLIED
                query-type CDATA #REQUIRED
                query-type (eq|like|in)>
        <!ELEMENT result-map (result*)>
        <!ATTLIST result-map
                enable-default (true|false) #REQUIRED
                default-result-key CDATA #IMPLIED>
        <!ELEMENT result ()>
        <!ATTLIST result
                raw-key CDATA #REQUIRED
                show-key CDATA #IMPLIED
                raw-type CDATA #IMPLIED
                show-type CDATA #IMPLIED>
        <!ELEMENT convert-list (dict-convert* bean-convert*)>
        <!ELEMENT dict-convert ()>
        <!ATTLIST dict-convert
                id CDATA #REQUIRED
                dict-type CDATA #REQUIRED
                show-key CDATA #REQUIRED>
        <!ELEMENT bean-convert ()>
        <!ATTLIST bean-convert
                id CDATA #REQUIRED
                bean CDATA #REQUIRED
                show-key CDATA #REQUIRED>

=== guo-Parsec/pinapple-project/pineapple-service-system/pineapple-system-core/src/main/resources/sys-dict-query-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "./query-config.dtd">
<config>
    <query-params>
        <param field-name="typeCode" query-type="eq"/>
        <param field-name="typeName" query-type="like"/>
    </query-params>

    <result-map enable-default="true">
        <result raw-key="typeCode"/>
        <result raw-key="typeName"/>
        <result raw-key="dictVal"/>
        <result raw-key="display"/>
        <result raw-key="sort"/>
        <result raw-key="userId"/>
    </result-map>

    <convert-list>
        <bean-convert id="userId" bean="userConverter" show-key="user"/>
    </convert-list>
</config>
